### PR TITLE
Make Site Live

### PR DESCRIPTION
**Pull request by gooshie**
- I cannot test that it is live on my end because I already have my site live.
- I am AFK until 2300 hrs UTC at which point I can help if needed.
- You should have little to do except maybe go into settings.

### CODE REVIEW

**Comment by gooshie** [comment]
The settings and renaming the repo cannot be done by pull request.

**Comment by amchagas** [comment]
That is fine, I think I can do that from this side?

**Comment by amchagas** [comment]
Hi, 
seems I'm not smart enough to get the proper theme working with the website :slightly_frowning_face: 
Any chance you could point out what is wrong when you have time?

**Comment by gooshie** [comment]
## Go to [your repo](https://github.com/FOSH-following-demand/FOSH_home).

^Click "your repo" above in this message^

- Top of page about the middle is a [Settings] tab on the right of all the tabs.
- (See 1st image below.)
- You must rename the "FOSH_home" repo to: "FOSH-following-demand.github.io"
- Within that same Settings scroll down to Section: "GitHub Pages"
- If the Heading has a green background the page is LIVE!
- IF NOT set it to "MASTER" branch. (Scroll down THIS message to 2nd image.)

## ===> Rename Repo as per Image

image

## ===> Set to MASTER branch

image

**Comment by gooshie** [comment]
## I have it live from my repo but your theme is a mess.
- Home Page ==> http://gooshie.me/FOSH_home/
- 404 Page ==> http://gooshie.me/FOSH_home/404

**Comment by amchagas** [comment]
Thanks!

**Comment by amchagas** [comment]
and yes, the theme is a mess. I thought I did all the necessary steps to simply use one of the many github.io suggestions from the settings, but something broke along the way

**Comment by gooshie** [comment]
I'd suggest copying out any content you've written into the README.md file and then delete the everything else and start fresh with one of the 7-8 SUPPORTED themes under that same settings tab where you see the green header and site address.

1. Copy any words/content you've written into the top/root README.md
1. Delete everything else.
1. Go into settings tab, scroll down to the green heading and pick a SUPPORTED theme
1. Look for [Change Theme] button.
1. Choose ONCE...choose wisely...NEVER change the theme AGAIN.
1. Pick the one that looks the most "Professional" and "Inviting."
1. I like in this order: Leap Day, Slate, Architect, Dinky, Modernist
1. Those themes would take very little work to be functional for the development site
1. I like "Leap Day" if we change the yellow band to maybe medium grey.

To change a theme it's best to create a new repo for the new theme and then rename the old theme to something else so you can then make the new theme the name needed to make it live like you have it now. There is a way to test the new theme and run it for development while you migrate. I won't explain that now. For now you just need ANY SUPPORTED theme just to create your first site that would be best used to explain you ultimate site ideas and goals and set up a development "hub" of sorts. A place to plan and demonstrate desired features with screenshots or text, etc.

image

**Pull request merged**
